"""Extract test failures from test-results.xml and emit GitHub Actions error annotations."""

import os
import sys
import xml.etree.ElementTree as ET


def main():
    xml_path = sys.argv[1] if len(sys.argv) > 1 else "test-results.xml"
    if not os.path.exists(xml_path):
        print("::error::test-results.xml was not generated by pytest.")
        return 1

    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        tests = root.attrib.get("tests", "0")
        failures = root.attrib.get("failures", "0")
        errors = root.attrib.get("errors", "0")
        print(f"::error::Test Suite Result: tests={tests}, failures={failures}, errors={errors}")

        for tc in tree.iter("testcase"):
            for f in list(tc.iter("failure")) + list(tc.iter("error")):
                msg = (f.attrib.get("message") or f.text or "Unknown test failure").strip()
                clean_msg = " ".join(msg.split())[:250]
                cls = tc.attrib.get("classname", "")
                name = tc.attrib.get("name", "")
                file_path = tc.attrib.get("file", "test")
                line = tc.attrib.get("line", "1")
                print(f"::error file={file_path},line={line},title={cls}.{name}::{clean_msg}")
    except Exception as e:
        print(f"::error::Failed to parse test-results.xml: {e}")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
